#' Serialize Error Trace to JSON
#'
#' This function serializes the trace from an `rlang` error object into a nested JSON structure.
#' The trace is filtered, processed, and converted into a nested format using the `nest_data` function,
#' which organizes the function calls based on their parent-child relationships. The resulting trace is then
#' serialized into a JSON object for easy inspection or logging.
#'
#' @author Nathan C. Layman
#'
#' @param e An error object generated by `rlang`. It must contain a `trace` component, which is a dataframe-like structure.
#' @param drop A boolean value indicating whether to filter and include only visible trace entries (i.e., where `visible == TRUE`).
#' Default is TRUE.
#'
#' @return A nested JSON string representing the structured error trace.
#'
#' @note This function requires the `dplyr` and `jsonlite` packages for filtering and JSON serialization. It relies on
#' the `nest_data` function to handle nesting of trace data before serialization.
#'
#' @examples
#' tryCatch(
#'     sqrt("a"),
#'     error = function(e) {
#'     print(serialize_trace(e))
#' })
#'
#' @export
serialize_trace <- function(e, drop = T) {
  trace <- as.data.frame(e$trace) |> dplyr::rowwise() |> dplyr::mutate(call = paste(deparse(call), collapse = "\n"))
  if(drop) trace <- trace |> dplyr::filter(visible == T)
  trace <- nest_data(trace) |> jsonlite::toJSON(auto_unbox = TRUE)
}

#' Nest Data for Error Trace Serialization
#'
#' This function is used to recursively nest a dataframe of error trace calls for serialization
#' into a structured JSON format. It is primarily utilized in conjunction with the `serialize_trace`
#' function to process and organize error trace data into a nested hierarchy based on parent-child
#' relationships between function calls.
#'
#' @author Nathan C. Layman
#'
#' @param data A dataframe containing error trace data, with at least `call` and `parent` columns.
#' @param parent_id A numeric value representing the parent ID of the current call in the trace. Default is 0.
#' @param level_name A string representing the name of the current level of the trace. Default is NULL.
#'
#' @return A nested list representing the hierarchy of error trace calls. If no nested levels exist,
#' the function returns the current level name; otherwise, it returns a named list containing the nested structure.
#'
#' @note This function uses `dplyr` for data manipulation, `purrr` for recursion, and `stats` for creating
#' named lists with `setNames`. It is a key part of the error trace serialization process, as seen in the
#' `serialize_trace` function.
#'
#' @examples
#' # Used within the `serialize_trace` function to organize and serialize trace data:
#' tryCatch(
#'     sqrt("a"),
#'     error = function(e) {
#'     print(serialize_trace(e))
#' })
nest_data <- function(data, parent_id = 0, level_name = NULL) {

  subset <- data |> dplyr::filter(parent == parent_id)

  nested_list <- subset$call %>%
    purrr::map(~nest_data(data, match(.x, data$call), .x)) |>
    unlist(recursive = FALSE)

  if (length(nested_list) == 0) {
    return(level_name)
  }

  return(stats::setNames(list(nested_list), level_name))
}
